import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Category from '../components/Home/Category'
import Features from '../components/Home/Features'
import Footer from '../components/Footer'
// import Particle from '../components/Particle'
import Main from '../components/Main'


export default function Home() {

  return (
    <div className={styles.container}>

      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Main />
       
        {/* <div className='w-{500}'>
          <Particle />
        </div> */}
      </main>


      <Category />
      <Features />

      <footer className={styles.footer}>
        Powered by{' '}
        <span className={styles.logo}>
          <strong>PSR</strong>
        </span>
      </footer>
      <Footer />





      
    </div>
  )
}
