import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>


        <h1 className={styles.title}>
          Welcome to  <strong className={styles.strong2}>My Blog!</strong>
        </h1>

        <p className={styles.description}>
          Get Ready for new Blog Post !!
        </p>

        <div className={styles.grid}>

          {/* <Link href='/About' className={styles.card}><h2>Javascript &rarr;</h2></Link> */}
          <div className={styles.card} >
            <Link href={"/Blog"}><h2>Popular Blogs &rarr;</h2></Link>
            <p>Find in-depth information about Next.js features and API.</p>
          </div>
          <div className={styles.card} >
            <Link href={"/Blog"} ><h2>Learn &rarr;</h2></Link>
            <p>Learn about Next.js in an interactive course with quizzes!</p>

          </div>
          <div className={styles.card} >
            <Link href={"/Blog"}><h2>Top Rated &rarr;</h2></Link>
            <p>Find in-depth information about Next.js features and API.</p>
          </div>
          <div className={styles.card} >
            <Link href={"/Blog"} ><h2>More &rarr;</h2></Link>
            <p>Learn about Next.js in an interactive course with quizzes!</p>

          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <strong>PSR</strong>
          </span>
        </a>
      </footer>
    </div>
  )
}
