import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Category from '../components/Home/Category'
import Features from '../components/Home/Features'
import Footer from '../components/Footer'
import Main from '../components/Main'
import Rain from '../components/Rain'


export default function Home() {

  return (
    <div >

      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Rain />
        <Main />
      </main>
      <Category />
      <Features />
      <footer className={styles.footer}>
        Powered by{' '}
        <span className={styles.logo}>
          <strong>PSR</strong>
        </span>
      </footer>
      <Footer />
    </div>
  )
}
